INSERT INTO `todo` (`name`, `image`) VALUES
('Live Alone', 'http://shallow.codes/images_CR13/event01_live_alone_movie.jpg'),
('All out Comets', 'http://shallow.codes/images_CR13/event03_all_comets_music.jpg'),
('Debbie Hill', 'http://shallow.codes/images_CR13/event10_debbie_hill_music.jpg'),
('Blurred System', 'http://shallow.codes/images_CR13/event06_blurred_system_music.jpg'),
('Thames Marathon', 'http://shallow.codes/images_CR13/event34_thames_marathon_sport.jpg'),
('Celestial Ridge', 'http://shallow.codes/images_CR13/event09_celestial_ridge_show.jpg'),
('Moonlit Circus', 'http://shallow.codes/images_CR13/event24_moonlit_circus_show.jpg'),
('Love Happens', 'http://shallow.codes/images_CR13/event11_love_happens_movie.jpg'),
('NFL Europe Finals', 'http://shallow.codes/images_CR13/event12_efl_finals_sport.jpg'),
('The Search', 'http://shallow.codes/images_CR13/event35_the_search_movie.jpg'),
('Swimming Championship', 'http://shallow.codes/images_CR13/event13_european_champ_sport.jpg'),
('Westend Show', 'http://shallow.codes/images_CR13/event39_westend_show.jpg'),
('Carson vs. James', 'http://shallow.codes/images_CR13/event08_carson_james_sport.jpg'),
('Harper Street Festival', 'http://shallow.codes/images_CR13/event15_harper_festival_music.jpg'),
('Paddington Masters', 'http://shallow.codes/images_CR13/event28_paddington_masters_sport.jpg'),
('Joy of Sin', 'http://shallow.codes/images_CR13/event19_joy_sin_music.jpg'),
('Freedom', 'http://shallow.codes/images_CR13/event17_freedom_movie.jpg'),
('Invasion', 'http://shallow.codes/images_CR13/event18_invasion_movie.jpg'),
('Around London', 'http://shallow.codes/images_CR13/event04_around_london_sport.jpg'),
('Hamton vs. Surrey', 'http://shallow.codes/images_CR13/event14_hamton_surrey_sport.jpg'),
('Juice', 'http://shallow.codes/images_CR13/event20_juice_music.jpg'),
('Kelsey Nova', 'http://shallow.codes/images_CR13/event21_kelsey_nova_music.jpg'),
('A Bug`s Life', 'http://shallow.codes/images_CR13/event22_bugs_life_movie.jpg'),
('Andromeda', 'http://shallow.codes/images_CR13/event23_andromeda_movie.jpg'),
('Nicolas Josh', 'http://shallow.codes/images_CR13/event25_nicolas_josh_music.jpg'),
('Yuletide Cheer', 'http://shallow.codes/images_CR13/event40_yuletide_cheer_show.jpg'),
('Super Cars', 'http://shallow.codes/images_CR13/event33_super_cars_sport.jpg'),
('Nightfire Show', 'http://shallow.codes/images_CR13/event26_nightfire_show.jpg'),
('Alkazam', 'http://shallow.codes/images_CR13/event02_alkazam_show.jpg'),
('Artistic Tides', 'http://shallow.codes/images_CR13/event05_artistic_tides_show.jpg'),
('Origin', 'http://shallow.codes/images_CR13/event27_origin_movie.jpg'),
('Velvet', 'http://shallow.codes/images_CR13/event37_velvet_music.jpg'),
('Pantomime Show', 'http://shallow.codes/images_CR13/event29_pantomime_show.jpg'),
('Riot of Madness', 'http://shallow.codes/images_CR13/event30_riot_madness_music.jpg'),
('Wayup Radio Show', 'http://shallow.codes/images_CR13/event38_wayup_radio_show.jpg'),
('Royal Art Exhibition', 'http://shallow.codes/images_CR13/event31_royal_exhibition_show.jpg'),
('Haunted', 'http://shallow.codes/images_CR13/event16_haunted_movie.jpg'),
('Skate or die', 'http://shallow.codes/images_CR13/event32_skate_die_sport.jpg'),
('Twilight', 'http://shallow.codes/images_CR13/event36_twilight_movie.jpg'),
('Breakdance Cup', 'http://shallow.codes/images_CR13/event07_breakdance_cup_sport.jpg')
